name: DisplayDamage
main: org.sobadfish.displaydamage.PluginMain
version: 1.0.3
api:
  - 1.0.14
author: Sobadfish


load: STARTUP

commands:
  dpd:
    description: "设置是否显示伤害粒子"
    permission: default

